# Generated by Django 4.0.1 on 2022-01-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroapp',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
