# Generated by Django 4.0.1 on 2022-01-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes_app', '0002_superheroapp_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superheroapp',
            name='photo',
            field=models.ImageField(default='/images/default.jpg', upload_to='images/'),
        ),
    ]
